# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 989e384f10a4c9f54f2cbc7659abe6e0824d0df657628249c439c6b409c45215550b6adeb4bfcf1a07a83545d2a41e05fad46732841ec4ce1f47f536aeb136fd

test:
  secret_key_base: 6be33b8c89d61a99ed224706b6928a1730b72e1ff2d9157dd12e760f52db0c7fae843471a43a5d6bb86e12509bb0c857bcf1e1ef1e1a7e2c7addfa29968ccb30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
